version: '3.3'
services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: 125111317/lab5:compose-app
    container_name: my_app
    depends_on:
      - redis
    networks:
      - public
      - secret
    ports:
      - 80:5000
    volumes:
      - app-logs:/app/logs
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    image: 125111317/lab5:compose-tests
    container_name: my_tests
    depends_on:
      - app
    networks:
      - public
  redis:
    image: redis:alpine
    container_name: my_redis
    volumes:
      - redis-data:/data
    networks:
      - secret
volumes:
  redis-data:
    driver: local
  app-logs:
    driver: local

networks:
  secret:
    driver: bridge
  public:
    driver: bridge
